# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM apache/spark-py as base

LABEL maintainer="Douglas Martins <douglas.capelossi@gmail.com>"
USER root

RUN wget https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
RUN mv postgresql-42.2.5.jar /opt/spark/jars

COPY requirements-flask.txt .
RUN pip3 install -r requirements-flask.txt

ADD . /opt/spark/jars

# SET SPARK ENV VARIABLES
ENV CLASSPATH /opt/spark/jars/postgresql-42.2.5.jar

# SET PYSPARK VARIABLES
ENV PYTHONPATH="${SPARK_HOME}/python/:$PYTHONPATH"
ENV PYTHONSTARTUP=api.py
ENV FLASK_APP=api.py

ADD /src/api.py .

WORKDIR /app

COPY /src/api.py /app

COPY . . 

EXPOSE 5000

CMD ["python3","/app/src/api.py"]

