version: '3'                                                                                       
services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
    networks:
      - myNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app-flask:
      container_name: timescale_assignment_flask
      image: timescale_assignment_flask:latest
      build:
        context: .
        dockerfile: Dockerfile-flask
      ports:
        - 5000:5000
      depends_on:
        db:
          condition: service_healthy
      networks:
        - myNetwork
      volumes:
        - ./:/app
      env_file: .env
  app-tests:
    container_name: timescale_assignment_test
    image: timescale_assignment_test:latest
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - 8001:8001
    depends_on:
      - app-flask
    networks:
      - myNetwork
    volumes:
      - ./:/app
    env_file: .env
networks:
  myNetwork:
    driver: bridge